### ISSUE TITLE
建议：将 https://api.bspapp.com/client 域名配置成参数

### ISSUE THREAD

**Issue by youxiaohou** [79W/uni-cloud-storage#1]
将 https://api.bspapp.com/client 域名配置成参数，这样的话浏览器前端可以自定义域名+nginx反代，不会报跨域错误。

否则只能先传到后端使用 nodejs 来请求，没法直接通过浏览器上传。

**Comment by 79W** [comment]
> 将 https://api.bspapp.com/client 域名配置成参数，这样的话浏览器前端可以自定义域名+nginx反代，不会报跨域错误。
> 
> 否则只能先传到后端使用 nodejs 来请求，没法直接通过浏览器上传。


好的这个问题我会看下 当时我在编写的时候 没有发现有跨域的问题 可能是uniapp那边更新了
